### ISSUE TITLE
Tag post-release should not fail

### ISSUE THREAD

**Issue by Wokarol** [PinkGuruGames/SpaceScrapper#2]
Currently, "Tag post-release" fails if the tag is not found, that is, if the PR is not a release apparently.
That should not happen and the workflow should be skipped if that is the case.

**Comment by lucasstarsz** [comment]
I see. I'll look into it when I wake up.

**Comment by lucasstarsz** [comment]
https://github.com/PinkGuruGames/SpaceScrapper/blob/c26177fe1f401b1d47f59903bb442c1047eac36b/.github/workflows/tag-and-sync.yml#L12-L13

Even though this was included in the file before #1, it appears to possibly not be executing the second option...or it is somehow incorrect. I'll throw it into a test action on a separate repo and see if I can figure out the issue.

**Comment by lucasstarsz** [comment]
I've figured out the issue with the github action: the if statement was incorrectly made!

`${{ x }} && ${{ y }}` is different from `${{ x & y }}`, apparently. The more you know 😛
